---
# tasks file for dev

- name: Copy SQL file to DB host
  copy: src=ClientCreate.sql  dest=/home/ps{{sid}}/ClientCreate.sql  owner="{{ ps_user }}" group="{{ ps_user }}"
  when: type == "DB" and "'d' in sid[0]"
  register: cp_sql

- name: Run SQL file as SYS user
  shell: su - "{{ ps_user }}" -c "sqlplus "/as sysdba" @{{lnx_home}}/ClientCreate.sql"
  when: type == "DB" and cp_sql|success and "'d' in sid[0]"
  register: exec_sql

- name: Copy and Unzip PCM_Scripts
  unarchive: src=PCM_Scripts.zip dest="{{ lnx_home }}" owner="{{ ps_user }}" group="{{ ps_user }}"
  when: type == "MT" and "ansible_system' == "Linux" and get_db_info|success and "'d' in sid[0]"
  register: unzip_pcm_script

- name: Schedule PCM client script in Cron
  cron: name="PCM Client Script" minute="*/5" job="sh {{lnx_home}}/scripts/pcm/codes/{{client_script}}_Demo.sh > {{lnx_home}}/scripts/pcm/backups/logs/PCM_FM_DEMO.log"
  when: type == "MT" and "ansible_system' == "Linux" and unzip_pcm_script|success and "'d' in sid[0]"
  register: sched_pcm_script

- name: Copy PCM_Scripts on windows
  win_copy: src="{{ pcm_script }}" dest={{win_home}}\{{pcm_script}}
  when: type == "MT" and "ansible_system' == "Windows" and sched_pcm_script|success and "'d' in sid[0]"
  register: cp_pcm_script_win

- name: Unzip PCM_Scripts on Windows
  win_unzip: src="{{ pcm_script }}" dest={{win_home}}
  when: type == "MT" and "ansible_system' == "Windows" and cp_pcm_script_win|success and "'d' in sid[0]"
  register: unzip_pcm_script_win

- name: Schedule PCM_Scripts on Windows
  win_scheduled_task: name="PCM Client Script" execute="{{win_home}}\scripts\pcm\codes\{{client_script}}_Dev.bat"  frequency="minute" time="5" enable=yes state=present user="{{ ps_user }}"
  when: type == "MT" and "ansible_system' == "Windows" and unzip_pcm_script_win|success and "'d' in sid[0]"
  register: sched_pcm_script_win
