alter user PS identified by PS;

Grant connect,create session,create any table to PS;

connect PS/PS

CREATE TABLE PS_M_CLT_CFG_TBL (M_INSTANCE_NAME VARCHAR2(15) NOT NULL,
   M_UNX_SYNC_PATH VARCHAR2(180) NOT NULL,
   M_WIN_SYNC_PATH VARCHAR2(180) NOT NULL,
   M_FILE_EXTN_SYNC VARCHAR2(50) NOT NULL,
   M_BACKUP_FLAG VARCHAR2(10) NOT NULL,
   M_BKP_LOC_UNX VARCHAR2(150) NOT NULL,
   M_BKP_LOC_WIN VARCHAR2(150) NOT NULL,
   M_RETENTION_DAYS SMALLINT NOT NULL,
   M_EMAILID VARCHAR2(250) NOT NULL,
   M_CLNT_SNC_TIMEOUT SMALLINT NOT NULL,
   M_TIMEOUT SMALLINT NOT NULL,
   M_LASTUPDDTTM tIMESTAMP,
   M_BACKUP_LOCATION VARCHAR2(100) NOT NULL,
   M_RETENTION_WIN SMALLINT NOT NULL,
   M_ADD_CLNP_LOC VARCHAR2(150) NOT NULL,
   M_HEARTBEAT SMALLINT NOT NULL) TABLESPACE PSDEFAULT STORAGE (INITIAL
 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10
 PCTUSED 80
/
CREATE UNIQUE  iNDEX PS_M_CLT_CFG_TBL ON PS_M_CLT_CFG_TBL
 (M_INSTANCE_NAME) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL
 NOLOGGING
/
ALTER INDEX PS_M_CLT_CFG_TBL NOPARALLEL LOGGING
/
CREATE TABLE PS_M_CLT_STATUS (M_INSTANCE_NAME VARCHAR2(15) NOT NULL,
   M_HOST_TYPE VARCHAR2(10) NOT NULL,
   M_HOST_NAME VARCHAR2(60) NOT NULL,
   M_STATUS VARCHAR2(100) NOT NULL,
   M_LASTUPDDTTM tIMESTAMP,
   M_FULL_SYNC tIMESTAMP,
   M_COMMENTS VARCHAR2(254) NOT NULL) TABLESPACE PSDEFAULT STORAGE
 (INITIAL 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0)
 PCTFREE 10 PCTUSED 80
/
CREATE TABLE PS_M_FILE_CLT_TBL (M_REQUEST_ID VARCHAR2(15) NOT NULL,
   M_SOURCE_HOSTNAME VARCHAR2(40) NOT NULL,
   M_FILE_NAME VARCHAR2(20) NOT NULL,
   M_LOCATION VARCHAR2(20) NOT NULL,
   M_TARGET_HOSTNAME VARCHAR2(40) NOT NULL,
   M_MD5 VARCHAR2(32),
   M_FILE_SIZE DECIMAL(10) NOT NULL,
   M_STATUS VARCHAR2(100) NOT NULL,
   M_ACTION VARCHAR2(15) NOT NULL,
   M_REQ_DATE tIMESTAMP,
   M_COMMENTS VARCHAR2(254) NOT NULL,
   M_ZIP_FILE BLOB) TABLESPACE PSDEFAULT STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PCTUSED 80
/
CREATE TABLE PS_M_FILE_REPSTORY (M_INSTANCE_NAME VARCHAR2(15) NOT NULL
,
   M_HOST_NAME VARCHAR2(60) NOT NULL,
   M_HOST_TYPE VARCHAR2(10) NOT NULL,
   M_FILE_TYPE VARCHAR2(20) NOT NULL,
   M_FILE_NAME VARCHAR2(40) NOT NULL,
   M_LOCATION VARCHAR2(20) NOT NULL,
   M_MODIFIED_DATE tIMESTAMP,
   M_SIZE DECIMAL(13, 3) NOT NULL,
   M_MD5 VARCHAR2(32) NOT NULL,
   M_SYNCHRONIZED VARCHAR2(1) NOT NULL) TABLESPACE PSDEFAULT STORAGE
 (INITIAL 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0)
 PCTFREE 10 PCTUSED 80
/
CREATE UNIQUE  iNDEX PS_M_FILE_REPSTORY ON PS_M_FILE_REPSTORY
 (M_INSTANCE_NAME,
   M_HOST_NAME,
   M_HOST_TYPE,
   M_FILE_TYPE,
   M_FILE_NAME,
   M_LOCATION) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_M_FILE_REPSTORY NOPARALLEL LOGGING
/

CONN / AS SYSDBA

revoke connect,create any table,create session from PS;


grant SELECT,INSERT,DELETE,UPDATE ON PS.PS_M_CLT_CFG_TBL TO people;
grant SELECT,INSERT,DELETE,UPDATE ON PS.PS_M_CLT_STATUS TO PEOPLE;
grant SELECT,INSERT,DELETE,UPDATE ON PS.PS_M_FILE_CLT_TBL  TO PEOPLE;
grant SELECT,INSERT,DELETE,UPDATE ON PS.PS_M_FILE_REPSTORY TO PEOPLE;

commit;
exit;
