INSERT INTO SYSADM.PS_SERVERCLASS VALUES('PCM',2,'AEPCM',5,3);
DELETE FROM SYSADM.PS_SERVERCLASS where SERVERNAME='PCM' and PRCSTYPE <> 'AEPCM';
UPDATE SYSADM.PS_PRCSDEFN SET MAXCONCURRENT=1 WHERE PRCSNAME IN ('M_MIGRATE_AE','M_MIGPROD_AE','M_PRD_TSTCON','M_DB_TESTCON');
commit;
exit;
